name: app_initial_structure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.3
  
  # Navigation
  auto_route: ^7.8.4
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Functional Programming
  dartz: ^0.10.1

  flutter_gen: 5.6.0
  
  # Annotations
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  
  # UI
  confetti: ^0.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  
  # Utilities
  logger: ^2.0.2
  package_info_plus: ^5.0.1
  
  # Asset Generation
  flutter_svg: ^2.0.9
  iconify_flutter:
    path: ./Iconify_custom

dev_dependencies:
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

# Flutter Gen Configuration
flutter_gen:
  output: lib/gen/
  line_length: 80
  
  integrations:
    flutter_svg: true
  
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter
      class_name: Assets
  
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily
  
  colors:
    enabled: false
